### ISSUE TITLE
Feature request: Switch to kingpin

### ISSUE THREAD

**Issue by mjtrangoni** [noony/prometheus-solr-exporter#4]
Hi,

Prometheus and many exporters are switching to kingpin. See also prometheus#2455. You will have to do some prometheus vendoring updates, but it should work as a drop-in replacement.

Thanks!

**Comment by noony** [comment]
Hey, thanks, nice catch, I'll do a commit tonight, thanks for the recommendation.

**Comment by noony** [comment]
Done.
