### ISSUE TITLE
Issue with version 0.0.5 solr_exporter

### ISSUE THREAD

**Issue by ganeshkumarpv** [noony/prometheus-solr-exporter#7]
Hi I downloaded the latest version 0.0.5 of solr_exporter and I am seeing a couple issues.
FYI : I saw the same behaviour also in 0.0.4 too.
1) solr_up is always showing 0 (down), despite its up. I am can see metrics like solr_process_virtual_memory_bytes, solr_process_cpu_seconds_total etc with real values.. but NOT solr_up metric.
2) I see the below error in nohup.out
time="2017-10-03T19:38:46-04:00" level=error msg="Failed to unmarshal mbeans cache metrics JSON into struct: json: cannot unmarshal number into Go struct field .hitratio of type string" source="exporter.go:388"
time="2017-10-03T19:38:56-04:00" level=error msg="Failed to unmarshal mbeans cache metrics JSON into struct: json: cannot unmarshal number into Go struct field .hitratio of type string" source="exporter.go:388"
time="2017-10-03T19:39:06-04:00" level=error msg="Failed to unmarshal mbeans cache metrics JSON into struct: json: cannot unmarshal number into Go struct field .hitratio of type string" source="exporter.go:388"
time="2017-10-03T19:39:16-04:00" level=error msg="Failed to unmarshal mbeans cache metrics JSON into struct: json: cannot unmarshal number into Go struct field .hitratio of type string" source="exporter.go:388"

Appreciate any help to address these issues.
Thanks,
Ganesh

**Comment by noony** [comment]
Hi@ganeshkumarpv , thanks for reporting, can you send the value of hitratio of this url please : 

http://YOUR_SOLR_URL:8983/solr/YOUR_CORE/admin/mbeans?stats=true&wt=json&cat=CORE&cat=QUERYHANDLER&cat=UPDATEHANDLER&cat=CACHE

Thanks.

**Comment by ganeshkumarpv** [comment]
Well. Since none of the metrics in grafana dashboard is getting populated, we are looking at jmx exporter. Thinking that it will be able to capture most of the metrics... 
Thanks for your help.

**Comment by noony** [comment]
Ok @ganeshkumarpv . But you didn't help me so much to resolve your issue. Sorry :(
